/////////////////////////////////////////////////////////////
//
// SceneDocumentor :: Global ID definition
//
/////////////////////////////////////////////////////////////
//
// Global ID definition
//
/////////////////////////////////////////////////////////////
// 2009-2010 by www.c4d-jack.de
// OpenSource. No warranty, no support.
/////////////////////////////////////////////////////////////

enum
{
	// string table definitions
	IDS_TCOMMENT	= 10000,
	IDS_TCOMMENT_HELPTEXT,
	IDS_COMMENT_TITLE,
	IDS_CREATECOMMENTNULL_INC_OPNAME,
	IDS_CREATECOMMENTNULL_INC_TITLE,
	IDS_CREATECOMMENTNULLS,
	IDS_CREATECOMMENTNULLS_HELP,
	IDS_CREATECOMMENTNULLS_STATUS,
	IDS_REMOVEALLTAGS,
	IDS_REMOVEALLTAGS_HELP,
	IDS_REMOVEALLTAGS_QUESTION,
	IDS_REMOVEALLTAGS_QUESTION_SELECTED,
	IDS_REMOVEALLTAGS_STATUS,
	IDS_NULLPARENT,
	IDS_CREATEDOCUMENT,
	IDS_CREATEDOCUMENT_HELP,
	IDS_CREATEDOCUMENT_STATUS,
	IDS_CREATEDOCUMENT_DLGTITLE_SAVEFILE,
	IDS_CREATEDOCUMENT_ERRORMSG,
	IDS_CREATEDOCUMENT_DONE,
	IDS_RENDERIMAGE_ERRORMSG,
	IDS_RENDERIMAGE_RUNNING,
	IDS_RENDERIMAGE_HTML_NOIMAGE,
	IDS_RENDERIMAGE_MSG_NOMEM,
	IDS_RENDERIMAGE_MSG_TEXMISSING,
	IDS_RENDERIMAGE_MSG_MP,
	IDS_RENDERIMAGE_MSG_IMAGE,
	IDS_RENDERIMAGE_MSG_USERBREAK,
	IDS_HELP_ERROR,
	IDS_OPENHELP,
	IDS_OPENHELP_HELP,

	IDS_CDOC_DLGTITLE,
	IDS_CDOC_GRP_FILENAME,
	IDS_CDOC_FILENAME,
	IDS_CDOC_OBJECT,
	IDS_CDOC_GRP_ADDINFO,
	IDS_CDOC_TITLE,
	IDS_CDOC_AUTHOR,
	IDS_CDOC_INTROTXT,
	IDS_CDOC_GRP_SETTINGS,
	IDS_CDOC_GRP_SETTINGS_IMAGE,
	IDS_CDOC_IMAGE_EDITOR,
	IDS_CDOC_IMAGE_RENDER,
	IDS_CDOC_IMAGE_WIDTH,
	IDS_CDOC_IMAGE_HEIGHT,
	IDS_CDOC_OPENDOCUMENT,
	IDS_CDOC_GRP_TEMPLATE,
	IDS_CDOC_TMPLDIR_INFO,
	IDS_CDOC_TMPLDIR,
	IDS_CDOC_TMPLDIR_OPEN,
	IDS_CDOC_GENERATE,
	IDS_CDOC_HELP,

	IDS_COMMENTINSPECTOR,
	IDS_COMMENTINSPECTOR_HELP,
	IDS_CINSP_DLGTITLE,
	IDS_CINSP_GRP_MAIN,
	IDS_CINSP_USECHILDREN,

	// End of symbol definition
	_DUMMY_ELEMENT_
};
